### ISSUE TITLE
Help Dan with his Energy Star Portfolio Manager Import error

### ISSUE THREAD

**Issue by haneslinger** [SEED-platform/seed#3593]
From Dan: 

Currently, when I try to use the Import Portfolio Manager data to add data to SEED, I’m getting an Internal Server Error after entering my ESPM credentials. I’ve double checked that the credentials are correct, and this feature did work in the past.

![Image](https://user-images.githubusercontent.com/30241543/200662164-79712540-082a-45c5-be44-e4739daec56a.png)

 
We are using SEED version: 2.15.1.faa47b69b

**Comment by haneslinger** [comment]
(https://github.com/SEED-platform/seed/pull/3592)

**Comment by haneslinger** [comment]
[groups.io](https://lists.buildingenergytools.org/g/SEEDusers/topic/seed_bug_espm_data_pull/94746918?p=,,,20,0,0,0::recentpostdate/sticky,,,20,2,0,94746918,previd%3D9223372036854775807,nextid%3D1607714259070094586&previd=9223372036854775807&nextid=1607714259070094586) thread

**Comment by RDmitchell** [comment]
@haneslinger / @nllong -- it seems like we have resolved all of Dan's issues? Can we close this?

**Comment by haneslinger** [comment]
I believe this was fixed [here](https://github.com/SEED-platform/seed/pull/3632)

**Comment by RDmitchell** [comment]
@nllong -- I guess they deploy their own instance, so because I communicated to him that I fixed this issue, can we close it, until we hear from him that with the new release it still isn't working?
