### ISSUE TITLE
Reports -- multi year colors

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#423]
Right now the colors are a bit close together for the multi year data, at least in the example that I tested. 2012 and 2011 are varients of blue -- seems like we might want a completely different color? 

And in the long run, this is probably something we will want to give the user control over, ie, the color scheme (but that is for much later in 2016 if not beyond). 

For this example I was using the test data from Issue 65
https://drive.google.com/a/lbl.gov/folderview?id=0B3fTKpZ9Dx7LTmlyM2w0MHRKeVE&usp=sharing

![image](https://cloud.githubusercontent.com/assets/6314950/10258114/c4965df0-6910-11e5-9be8-8c1d3ff9d688.png)

**Comment by danielmcquillen** [comment]
I updated the palette to the following colors:

![image](https://cloud.githubusercontent.com/assets/119496/10327276/3c6c62fa-6cf1-11e5-9df5-923dc4d491b2.png)

Fix is here:

https://github.com/SEED-platform/seed/tree/423-redo-palette

I can do a PR if this palette looks good.

**Comment by RDmitchell** [comment]
I think these colors look good. What would the color order be?

**Comment by danielmcquillen** [comment]
["#458cc8","#779e1c","#f2c41d","#939495","#c83737", "#f18630"];
or, 
blue, green, yellow, grey, red, orange.

**Comment by RDmitchell** [comment]
This looks good to me. Go ahead and submit a PR for this.

**Comment by danielmcquillen** [comment]
Done. https://github.com/SEED-platform/seed/pull/433

**Comment by RDmitchell** [comment]
Assigned to myself for testing when the PR is merged

**Comment by RDmitchell** [comment]
I am still seeing the old colors, even when I do an incognito window

![image](https://cloud.githubusercontent.com/assets/6314950/10521376/584216a8-7324-11e5-934a-27a5948d2fa0.png)

**Comment by RDmitchell** [comment]
I see them now, after Miles did his magic. I think allowing the users to pick the colors is going to be something we will want to add in the future. I will make an issue for it, but not assign it to anyone -- it will probably be for later in FY 2016
![image](https://cloud.githubusercontent.com/assets/6314950/10526780/aadfbd62-7341-11e5-98be-5cdd3030b83e.png)
