### ISSUE TITLE
Delete buildings not working when filtering using labels

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#730]
Deleting buildings does not seem to be working when you apply a filter using the "Filter by Label" function. 

Here is an example:

1. Import the standard PM sample data file (512 records)
2. Accept the default mapping
3. Go to Building List
4. Filter on Postal Code = 10102; 53 records are returned
5. Select all of those records with the upper left checkbox
6. From the Building Actions pulldown, select Add/Remove labels
7. Create a new label called Zip 10102, color gray, click Add, and Done so that label gets applied to those 53 building records
8. Remove the filter so that the 512 buildings are again displayed.
9. In the Filter by Label box, pick the "Zip 10102" label, so that 53 records are displayed.
10. Select all of those records with the upper left checkbox
11. From the Building Actions pulldown, select Delete Buildings
12. The program asks if you are sure you want to delete the buildings, you say Yes, it appears from the dialog box that they are deleted.
13. But they are still displayed on the screen.
14. Remove the label filter, and click the update filters button so that all 512 records are displayed
15. The records with zip = 10102 are still there (that's why the program reports that there are 512 records) -- they did not get deleted.

**Comment by RDmitchell** [comment]
@nicholasserra -- am assigning this to you, as I am not sure if @pipermerriam still has time to work on seed. Feel free to give it to him if he does. Thx !

**Comment by pipermerriam** [comment]
@RDmitchell 

This should have been fixed with https://github.com/SEED-platform/seed/pull/720 which was merged 3 days ago.  Do you know whether you encountered this issue on a testing site that had this code deployed to it?

**Comment by RDmitchell** [comment]
I believe I tested this yesterday on seedtest, but let me test again and get back to you.

**Comment by RDmitchell** [comment]
Looking at the time I made this issue, 21 hours ago, I was testing the current code on seedtest, yesterday afternoon. So I am still seeing the problem. Do you want me to set up an account that shows the problem and invite you as a member?

**Comment by RDmitchell** [comment]
Let me know if you cannot reproduce this problem.

**Comment by pipermerriam** [comment]
No, not yet.  I'm still investigating.

On Tue, Feb 9, 2016 at 1:14 PM, RDmitchell <notifications@github.com> wrote:

> Looking at the time I made this issue, 21 hours ago, I was testing the
> current code on seedtest, yesterday afternoon. So I am still seeing the
> problem. Do you want me to set up an account that shows the problem and
> invite you as a member?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SEED-platform/seed/issues/730#issuecomment-182069975>.
>



-- 

*Piper Merriam | Senior Developer*

*Quick Left, Inc.
<http://www.google.com/url?q=http%3A%2F%2Fquickleft.com%2F&sa=D&sntz=1&usg=AFrqEzdP6K1wURnZfgF6QDUGS6O5EmLhTg>*
*Boulder & Denver, CO*

844.QL.NERDS

@pipermerriam

**Comment by RDmitchell** [comment]
assigned to myself for testing once PR is merged to seedtest

**Comment by RDmitchell** [comment]
this is working now ! Thanks !!!
